"""adicao do campo de telefone na tabela usuario

Revision ID: 533958b101c5
Revises: 
Create Date: 2025-09-18 08:04:28.029416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533958b101c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
